# -*- coding: utf-8 -*-
"""AI p2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBtcVVkYEsj9LnI4mDsWp4qhwFfK6an2
"""

# Step 1: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, f1_score, classification_report

# Step 2: Load Dataset
iris = load_iris()
X = iris.data        # Features: sepal length, sepal width, petal length, petal width
y = iris.target      # Labels: 0=Setosa, 1=Versicolor, 2=Virginica

print("Dataset Shape:", X.shape)
print("Classes:", iris.target_names)

# Step 3: Feature Scaling (StandardScaler)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Train-Test Split (80/20 with shuffle)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, shuffle=True
)
print(f"\nTraining samples: {len(X_train)}, Testing samples: {len(X_test)}")

# Step 5: Train KNN Model (k=5)
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Step 6: Make Predictions
predictions = model.predict(X_test)

# Step 7: Evaluate - Confusion Matrix
cm = confusion_matrix(y_test, predictions)
print("\nConfusion Matrix:\n", cm)

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names)
plt.title('Confusion Matrix - KNN (k=5)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.savefig('confusion_matrix.png')
plt.show()

# Step 8: Evaluate - F1 Score
f1 = f1_score(y_test, predictions, average='weighted')
print(f"\nF1 Score (Weighted): {f1:.4f}")
print("\nFull Classification Report:")
print(classification_report(y_test, predictions, target_names=iris.target_names))

# BONUS: Find optimal K using elbow method
error_rates = []
for k in range(1, 31):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    preds = knn.predict(X_test)
    error_rates.append(1 - f1_score(y_test, preds, average='weighted'))

plt.figure(figsize=(8, 4))
plt.plot(range(1, 31), error_rates, marker='o', color='navy')
plt.title('Elbow Method: Finding Optimal K')
plt.xlabel('K Value')
plt.ylabel('Error Rate')
plt.tight_layout()
plt.savefig('elbow_method.png')
plt.show()

print("\nOptimal K:", error_rates.index(min(error_rates)) + 1)