# -*- coding: utf-8 -*-
"""Ai p3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHkVv_4Wock8CEN3BOUnhk8Hp5DjO2Gx
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ─────────────────────────────────────────────
# DATASET: Job Roles and their required skills
# ─────────────────────────────────────────────
job_roles = {
    "Job Role": [
        "Data Scientist",
        "Machine Learning Engineer",
        "Backend Developer",
        "Frontend Developer",
        "DevOps Engineer",
        "Cloud Architect",
        "Cybersecurity Analyst",
        "Data Analyst",
        "Full Stack Developer",
        "AI Engineer",
        "Database Administrator",
        "Mobile App Developer",
        "Systems Administrator",
        "Blockchain Developer",
        "NLP Engineer"
    ],
    "Skills": [
        "python sql machine learning data analysis statistics pandas numpy visualization",
        "python tensorflow pytorch deep learning algorithms neural networks model training",
        "python java sql apis rest databases server django flask nodejs",
        "html css javascript react vue ui ux design frontend",
        "aws docker kubernetes ci cd linux automation devops pipelines git",
        "aws azure cloud infrastructure terraform networking automation scalability",
        "networking firewalls linux security encryption penetration testing ethical hacking",
        "sql excel tableau power bi statistics data visualization reporting business intelligence",
        "html css javascript react nodejs python databases apis full stack",
        "python machine learning deep learning nlp computer vision tensorflow pytorch algorithms",
        "sql mysql postgresql mongodb database design optimization backup administration",
        "swift kotlin java android ios mobile react native flutter app development",
        "linux networking servers automation bash scripting system administration",
        "solidity ethereum blockchain smart contracts web3 cryptography decentralized",
        "python nlp text processing transformers bert huggingface linguistics language models"
    ]
}

df = pd.DataFrame(job_roles)

# ─────────────────────────────────────────────
# STEP 1: INGESTION — Get skills one by one
# ─────────────────────────────────────────────
print("=" * 55)
print("   🤖 DecodeLabs Tech Stack Recommender")
print("=" * 55)
print("\nYou will enter your skills one by one.")
print("Minimum 3 skills required. Type 'done' when finished.\n")

user_skills = []
skill_number = 1

while True:
    skill = input(f"  Enter Skill #{skill_number}: ").strip().lower()

    if skill == "done":
        if len(user_skills) < 3:
            print(f"\n  ⚠️  You've only entered {len(user_skills)} skill(s).")
            print("  Please enter at least 3 skills before typing 'done'.\n")
        else:
            break
    elif skill == "":
        print("  ⚠️  Skill cannot be empty. Please try again.\n")
    else:
        user_skills.append(skill)
        print(f"  ✅ '{skill.title()}' added!\n")
        skill_number += 1

# Summary of entered skills
print("\n" + "─" * 55)
print("  📋 Skills You Entered:")
for i, s in enumerate(user_skills, 1):
    print(f"     {i}. {s.title()}")
print("─" * 55)

# ─────────────────────────────────────────────
# STEP 2: SCORING — TF-IDF + Cosine Similarity
# ─────────────────────────────────────────────
user_profile = " ".join(user_skills)

all_documents = df["Skills"].tolist() + [user_profile]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(all_documents)

user_vector = tfidf_matrix[-1]
job_vectors = tfidf_matrix[:-1]

similarity_scores = cosine_similarity(user_vector, job_vectors).flatten()

# ─────────────────────────────────────────────
# STEP 3: SORTING — Rank by score
# ─────────────────────────────────────────────
df["Similarity Score"] = similarity_scores
df_sorted = df.sort_values("Similarity Score", ascending=False)

# ─────────────────────────────────────────────
# STEP 4: FILTERING — Show Top 3 results
# ─────────────────────────────────────────────
top_n = 3
top_results = df_sorted.head(top_n)

print(f"\n  ✅ Top {top_n} Career Matches for Your Skills")
print("=" * 55)

for rank, (_, row) in enumerate(top_results.iterrows(), start=1):
    match_percent = round(row["Similarity Score"] * 100, 2)
    print(f"\n  #{rank}  {row['Job Role']}")
    print(f"       Match Score: {match_percent}%")

print("\n" + "=" * 55)
print("  💡 Tip: More specific skills = better matches!")
print("=" * 55)